# Generated by Django 5.1.1 on 2024-11-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblock', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
