# Generated by Django 5.1.1 on 2024-11-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblock', '0006_remove_profile_bio_remove_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
